[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_ldf_mode = deep+

lib_deps =
    adafruit/RTClib
    SPI
    SD
    adafruit/Adafruit BME280 Library @ ^2.1.2
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit SH110X @ ^2.1.15